yaskawa_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  gains:
    joint_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_joint
  gains:
    right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  gains:
    joint_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1