// Generated by gencpp from file sun_wsg50_common/Conf.msg
// DO NOT EDIT!


#ifndef SUN_WSG50_COMMON_MESSAGE_CONF_H
#define SUN_WSG50_COMMON_MESSAGE_CONF_H

#include <ros/service_traits.h>


#include <sun_wsg50_common/ConfRequest.h>
#include <sun_wsg50_common/ConfResponse.h>


namespace sun_wsg50_common
{

struct Conf
{

typedef ConfRequest Request;
typedef ConfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Conf
} // namespace sun_wsg50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_wsg50_common::Conf > {
  static const char* value()
  {
    return "0c7a1839200830facdc1205cf36615d5";
  }

  static const char* value(const ::sun_wsg50_common::Conf&) { return value(); }
};

template<>
struct DataType< ::sun_wsg50_common::Conf > {
  static const char* value()
  {
    return "sun_wsg50_common/Conf";
  }

  static const char* value(const ::sun_wsg50_common::Conf&) { return value(); }
};


// service_traits::MD5Sum< ::sun_wsg50_common::ConfRequest> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Conf >
template<>
struct MD5Sum< ::sun_wsg50_common::ConfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Conf >::value();
  }
  static const char* value(const ::sun_wsg50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::ConfRequest> should match
// service_traits::DataType< ::sun_wsg50_common::Conf >
template<>
struct DataType< ::sun_wsg50_common::ConfRequest>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Conf >::value();
  }
  static const char* value(const ::sun_wsg50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_wsg50_common::ConfResponse> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Conf >
template<>
struct MD5Sum< ::sun_wsg50_common::ConfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Conf >::value();
  }
  static const char* value(const ::sun_wsg50_common::ConfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::ConfResponse> should match
// service_traits::DataType< ::sun_wsg50_common::Conf >
template<>
struct DataType< ::sun_wsg50_common::ConfResponse>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Conf >::value();
  }
  static const char* value(const ::sun_wsg50_common::ConfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_WSG50_COMMON_MESSAGE_CONF_H
