// Generated by gencpp from file sun_wsg50_common/Incr.msg
// DO NOT EDIT!


#ifndef SUN_WSG50_COMMON_MESSAGE_INCR_H
#define SUN_WSG50_COMMON_MESSAGE_INCR_H

#include <ros/service_traits.h>


#include <sun_wsg50_common/IncrRequest.h>
#include <sun_wsg50_common/IncrResponse.h>


namespace sun_wsg50_common
{

struct Incr
{

typedef IncrRequest Request;
typedef IncrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Incr
} // namespace sun_wsg50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_wsg50_common::Incr > {
  static const char* value()
  {
    return "b996830260cb95e784a9d9fbb5e34c61";
  }

  static const char* value(const ::sun_wsg50_common::Incr&) { return value(); }
};

template<>
struct DataType< ::sun_wsg50_common::Incr > {
  static const char* value()
  {
    return "sun_wsg50_common/Incr";
  }

  static const char* value(const ::sun_wsg50_common::Incr&) { return value(); }
};


// service_traits::MD5Sum< ::sun_wsg50_common::IncrRequest> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Incr >
template<>
struct MD5Sum< ::sun_wsg50_common::IncrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Incr >::value();
  }
  static const char* value(const ::sun_wsg50_common::IncrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::IncrRequest> should match
// service_traits::DataType< ::sun_wsg50_common::Incr >
template<>
struct DataType< ::sun_wsg50_common::IncrRequest>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Incr >::value();
  }
  static const char* value(const ::sun_wsg50_common::IncrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_wsg50_common::IncrResponse> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Incr >
template<>
struct MD5Sum< ::sun_wsg50_common::IncrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Incr >::value();
  }
  static const char* value(const ::sun_wsg50_common::IncrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::IncrResponse> should match
// service_traits::DataType< ::sun_wsg50_common::Incr >
template<>
struct DataType< ::sun_wsg50_common::IncrResponse>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Incr >::value();
  }
  static const char* value(const ::sun_wsg50_common::IncrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_WSG50_COMMON_MESSAGE_INCR_H
