// Generated by gencpp from file sun_wsg50_common/MoveRequest.msg
// DO NOT EDIT!


#ifndef SUN_WSG50_COMMON_MESSAGE_MOVEREQUEST_H
#define SUN_WSG50_COMMON_MESSAGE_MOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sun_wsg50_common
{
template <class ContainerAllocator>
struct MoveRequest_
{
  typedef MoveRequest_<ContainerAllocator> Type;

  MoveRequest_()
    : width(0.0)
    , speed(0.0)  {
    }
  MoveRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRequest_

typedef ::sun_wsg50_common::MoveRequest_<std::allocator<void> > MoveRequest;

typedef boost::shared_ptr< ::sun_wsg50_common::MoveRequest > MoveRequestPtr;
typedef boost::shared_ptr< ::sun_wsg50_common::MoveRequest const> MoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_wsg50_common::MoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_wsg50_common::MoveRequest_<ContainerAllocator1> & lhs, const ::sun_wsg50_common::MoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_wsg50_common::MoveRequest_<ContainerAllocator1> & lhs, const ::sun_wsg50_common::MoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_wsg50_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2d4f46fe020a06d64128c90310c767d";
  }

  static const char* value(const ::sun_wsg50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2d4f46fe020a06dULL;
  static const uint64_t static_value2 = 0x64128c90310c767dULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_wsg50_common/MoveRequest";
  }

  static const char* value(const ::sun_wsg50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n"
"float32 speed\n"
;
  }

  static const char* value(const ::sun_wsg50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_wsg50_common::MoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_wsg50_common::MoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_WSG50_COMMON_MESSAGE_MOVEREQUEST_H
