// Generated by gencpp from file sun_wsg50_common/Move.msg
// DO NOT EDIT!


#ifndef SUN_WSG50_COMMON_MESSAGE_MOVE_H
#define SUN_WSG50_COMMON_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <sun_wsg50_common/MoveRequest.h>
#include <sun_wsg50_common/MoveResponse.h>


namespace sun_wsg50_common
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace sun_wsg50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_wsg50_common::Move > {
  static const char* value()
  {
    return "ac4bc9278b95c49c6bb95b3db7e0a0e4";
  }

  static const char* value(const ::sun_wsg50_common::Move&) { return value(); }
};

template<>
struct DataType< ::sun_wsg50_common::Move > {
  static const char* value()
  {
    return "sun_wsg50_common/Move";
  }

  static const char* value(const ::sun_wsg50_common::Move&) { return value(); }
};


// service_traits::MD5Sum< ::sun_wsg50_common::MoveRequest> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Move >
template<>
struct MD5Sum< ::sun_wsg50_common::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Move >::value();
  }
  static const char* value(const ::sun_wsg50_common::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::MoveRequest> should match
// service_traits::DataType< ::sun_wsg50_common::Move >
template<>
struct DataType< ::sun_wsg50_common::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Move >::value();
  }
  static const char* value(const ::sun_wsg50_common::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_wsg50_common::MoveResponse> should match
// service_traits::MD5Sum< ::sun_wsg50_common::Move >
template<>
struct MD5Sum< ::sun_wsg50_common::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_wsg50_common::Move >::value();
  }
  static const char* value(const ::sun_wsg50_common::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_wsg50_common::MoveResponse> should match
// service_traits::DataType< ::sun_wsg50_common::Move >
template<>
struct DataType< ::sun_wsg50_common::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::sun_wsg50_common::Move >::value();
  }
  static const char* value(const ::sun_wsg50_common::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_WSG50_COMMON_MESSAGE_MOVE_H
