// Generated by gencpp from file sun_wsg50_common/MoveResponse.msg
// DO NOT EDIT!


#ifndef SUN_WSG50_COMMON_MESSAGE_MOVERESPONSE_H
#define SUN_WSG50_COMMON_MESSAGE_MOVERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sun_wsg50_common
{
template <class ContainerAllocator>
struct MoveResponse_
{
  typedef MoveResponse_<ContainerAllocator> Type;

  MoveResponse_()
    : error(0)  {
    }
  MoveResponse_(const ContainerAllocator& _alloc)
    : error(0)  {
  (void)_alloc;
    }



   typedef uint8_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResponse_

typedef ::sun_wsg50_common::MoveResponse_<std::allocator<void> > MoveResponse;

typedef boost::shared_ptr< ::sun_wsg50_common::MoveResponse > MoveResponsePtr;
typedef boost::shared_ptr< ::sun_wsg50_common::MoveResponse const> MoveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_wsg50_common::MoveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_wsg50_common::MoveResponse_<ContainerAllocator1> & lhs, const ::sun_wsg50_common::MoveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_wsg50_common::MoveResponse_<ContainerAllocator1> & lhs, const ::sun_wsg50_common::MoveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_wsg50_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf8e3bc5443691736455ca47e3128027";
  }

  static const char* value(const ::sun_wsg50_common::MoveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf8e3bc544369173ULL;
  static const uint64_t static_value2 = 0x6455ca47e3128027ULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_wsg50_common/MoveResponse";
  }

  static const char* value(const ::sun_wsg50_common::MoveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 error\n"
"\n"
;
  }

  static const char* value(const ::sun_wsg50_common::MoveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_wsg50_common::MoveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_wsg50_common::MoveResponse_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_WSG50_COMMON_MESSAGE_MOVERESPONSE_H
