geometry_msgs/TransformStamped goal_transform
float64[] goal_joint 
string planning_group
string planning_type
float64[] start_state
bool attach
bool detach
string attach_obj_id
---
moveit_msgs/RobotTrajectory trajectory
bool success
