; Auto-generated. Do not edit!


(cl:in-package sun_robot_msgs-msg)


;//! \htmlinclude CartesianTrajectoryFeedback.msg.html

(cl:defclass <CartesianTrajectoryFeedback> (roslisp-msg-protocol:ros-message)
  ((time_left
    :reader time_left
    :initarg :time_left
    :type cl:real
    :initform 0))
)

(cl:defclass CartesianTrajectoryFeedback (<CartesianTrajectoryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CartesianTrajectoryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CartesianTrajectoryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sun_robot_msgs-msg:<CartesianTrajectoryFeedback> is deprecated: use sun_robot_msgs-msg:CartesianTrajectoryFeedback instead.")))

(cl:ensure-generic-function 'time_left-val :lambda-list '(m))
(cl:defmethod time_left-val ((m <CartesianTrajectoryFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sun_robot_msgs-msg:time_left-val is deprecated.  Use sun_robot_msgs-msg:time_left instead.")
  (time_left m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CartesianTrajectoryFeedback>) ostream)
  "Serializes a message object of type '<CartesianTrajectoryFeedback>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'time_left)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'time_left) (cl:floor (cl:slot-value msg 'time_left)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CartesianTrajectoryFeedback>) istream)
  "Deserializes a message object of type '<CartesianTrajectoryFeedback>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time_left) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CartesianTrajectoryFeedback>)))
  "Returns string type for a message object of type '<CartesianTrajectoryFeedback>"
  "sun_robot_msgs/CartesianTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CartesianTrajectoryFeedback)))
  "Returns string type for a message object of type 'CartesianTrajectoryFeedback"
  "sun_robot_msgs/CartesianTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CartesianTrajectoryFeedback>)))
  "Returns md5sum for a message object of type '<CartesianTrajectoryFeedback>"
  "df04f3fae3898e2a9dc2f391cd8efd73")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CartesianTrajectoryFeedback)))
  "Returns md5sum for a message object of type 'CartesianTrajectoryFeedback"
  "df04f3fae3898e2a9dc2f391cd8efd73")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CartesianTrajectoryFeedback>)))
  "Returns full string definition for message of type '<CartesianTrajectoryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%duration time_left~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CartesianTrajectoryFeedback)))
  "Returns full string definition for message of type 'CartesianTrajectoryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%duration time_left~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CartesianTrajectoryFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CartesianTrajectoryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CartesianTrajectoryFeedback
    (cl:cons ':time_left (time_left msg))
))
