; Auto-generated. Do not edit!


(cl:in-package sun_robot_msgs-msg)


;//! \htmlinclude CartesianTrajectoryResult.msg.html

(cl:defclass <CartesianTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CartesianTrajectoryResult (<CartesianTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CartesianTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CartesianTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sun_robot_msgs-msg:<CartesianTrajectoryResult> is deprecated: use sun_robot_msgs-msg:CartesianTrajectoryResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CartesianTrajectoryResult>) ostream)
  "Serializes a message object of type '<CartesianTrajectoryResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CartesianTrajectoryResult>) istream)
  "Deserializes a message object of type '<CartesianTrajectoryResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CartesianTrajectoryResult>)))
  "Returns string type for a message object of type '<CartesianTrajectoryResult>"
  "sun_robot_msgs/CartesianTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CartesianTrajectoryResult)))
  "Returns string type for a message object of type 'CartesianTrajectoryResult"
  "sun_robot_msgs/CartesianTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CartesianTrajectoryResult>)))
  "Returns md5sum for a message object of type '<CartesianTrajectoryResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CartesianTrajectoryResult)))
  "Returns md5sum for a message object of type 'CartesianTrajectoryResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CartesianTrajectoryResult>)))
  "Returns full string definition for message of type '<CartesianTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CartesianTrajectoryResult)))
  "Returns full string definition for message of type 'CartesianTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CartesianTrajectoryResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CartesianTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CartesianTrajectoryResult
))
