// Generated by gencpp from file sun_ros_msgs/MultiVector.msg
// DO NOT EDIT!


#ifndef SUN_ROS_MSGS_MESSAGE_MULTIVECTOR_H
#define SUN_ROS_MSGS_MESSAGE_MULTIVECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sun_ros_msgs
{
template <class ContainerAllocator>
struct MultiVector_
{
  typedef MultiVector_<ContainerAllocator> Type;

  MultiVector_()
    : data()  {
    }
  MultiVector_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sun_ros_msgs::MultiVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_ros_msgs::MultiVector_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVector_

typedef ::sun_ros_msgs::MultiVector_<std::allocator<void> > MultiVector;

typedef boost::shared_ptr< ::sun_ros_msgs::MultiVector > MultiVectorPtr;
typedef boost::shared_ptr< ::sun_ros_msgs::MultiVector const> MultiVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_ros_msgs::MultiVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_ros_msgs::MultiVector_<ContainerAllocator1> & lhs, const ::sun_ros_msgs::MultiVector_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_ros_msgs::MultiVector_<ContainerAllocator1> & lhs, const ::sun_ros_msgs::MultiVector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_ros_msgs::MultiVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_ros_msgs::MultiVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_ros_msgs::MultiVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::sun_ros_msgs::MultiVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_ros_msgs/MultiVector";
  }

  static const char* value(const ::sun_ros_msgs::MultiVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::sun_ros_msgs::MultiVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_ros_msgs::MultiVector_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROS_MSGS_MESSAGE_MULTIVECTOR_H
