// Generated by gencpp from file sun_ros_msgs/MultiVectorStamped.msg
// DO NOT EDIT!


#ifndef SUN_ROS_MSGS_MESSAGE_MULTIVECTORSTAMPED_H
#define SUN_ROS_MSGS_MESSAGE_MULTIVECTORSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sun_ros_msgs/MultiVector.h>

namespace sun_ros_msgs
{
template <class ContainerAllocator>
struct MultiVectorStamped_
{
  typedef MultiVectorStamped_<ContainerAllocator> Type;

  MultiVectorStamped_()
    : header()
    , data()  {
    }
  MultiVectorStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sun_ros_msgs::MultiVector_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVectorStamped_

typedef ::sun_ros_msgs::MultiVectorStamped_<std::allocator<void> > MultiVectorStamped;

typedef boost::shared_ptr< ::sun_ros_msgs::MultiVectorStamped > MultiVectorStampedPtr;
typedef boost::shared_ptr< ::sun_ros_msgs::MultiVectorStamped const> MultiVectorStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator1> & lhs, const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator1> & lhs, const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c082b7820de5e2776a5f02ae355e774";
  }

  static const char* value(const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c082b7820de5e27ULL;
  static const uint64_t static_value2 = 0x76a5f02ae355e774ULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_ros_msgs/MultiVectorStamped";
  }

  static const char* value(const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"MultiVector data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sun_ros_msgs/MultiVector\n"
"float64[] data\n"
;
  }

  static const char* value(const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVectorStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_ros_msgs::MultiVectorStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::sun_ros_msgs::MultiVector_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROS_MSGS_MESSAGE_MULTIVECTORSTAMPED_H
