// Generated by gencpp from file pose_estimation/mask.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATION_MESSAGE_MASK_H
#define POSE_ESTIMATION_MESSAGE_MASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int8MultiArray.h>

namespace pose_estimation
{
template <class ContainerAllocator>
struct mask_
{
  typedef mask_<ContainerAllocator> Type;

  mask_()
    : header()
    , mask()
    , classes()  {
    }
  mask_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mask(_alloc)
    , classes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int8MultiArray_<ContainerAllocator>  _mask_type;
  _mask_type mask;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _classes_type;
  _classes_type classes;





  typedef boost::shared_ptr< ::pose_estimation::mask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_estimation::mask_<ContainerAllocator> const> ConstPtr;

}; // struct mask_

typedef ::pose_estimation::mask_<std::allocator<void> > mask;

typedef boost::shared_ptr< ::pose_estimation::mask > maskPtr;
typedef boost::shared_ptr< ::pose_estimation::mask const> maskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_estimation::mask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_estimation::mask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_estimation::mask_<ContainerAllocator1> & lhs, const ::pose_estimation::mask_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mask == rhs.mask &&
    lhs.classes == rhs.classes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_estimation::mask_<ContainerAllocator1> & lhs, const ::pose_estimation::mask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_estimation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_estimation::mask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimation::mask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimation::mask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimation::mask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimation::mask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimation::mask_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_estimation::mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9fdf2d4d86599b240a22049ffa0278e";
  }

  static const char* value(const ::pose_estimation::mask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9fdf2d4d86599b2ULL;
  static const uint64_t static_value2 = 0x40a22049ffa0278eULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_estimation::mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_estimation/mask";
  }

  static const char* value(const ::pose_estimation::mask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_estimation::mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Int8MultiArray mask\n"
"int8[] classes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int8[]            data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::pose_estimation::mask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_estimation::mask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mask);
      stream.next(m.classes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_estimation::mask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_estimation::mask_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mask: ";
    s << std::endl;
    Printer< ::std_msgs::Int8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.mask);
    s << indent << "classes[]" << std::endl;
    for (size_t i = 0; i < v.classes.size(); ++i)
    {
      s << indent << "  classes[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.classes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_ESTIMATION_MESSAGE_MASK_H
