// Generated by gencpp from file pose_estimation/plan_service.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATION_MESSAGE_PLAN_SERVICE_H
#define POSE_ESTIMATION_MESSAGE_PLAN_SERVICE_H

#include <ros/service_traits.h>


#include <pose_estimation/plan_serviceRequest.h>
#include <pose_estimation/plan_serviceResponse.h>


namespace pose_estimation
{

struct plan_service
{

typedef plan_serviceRequest Request;
typedef plan_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plan_service
} // namespace pose_estimation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_estimation::plan_service > {
  static const char* value()
  {
    return "f3dd71be87193ac42006527f8539da01";
  }

  static const char* value(const ::pose_estimation::plan_service&) { return value(); }
};

template<>
struct DataType< ::pose_estimation::plan_service > {
  static const char* value()
  {
    return "pose_estimation/plan_service";
  }

  static const char* value(const ::pose_estimation::plan_service&) { return value(); }
};


// service_traits::MD5Sum< ::pose_estimation::plan_serviceRequest> should match
// service_traits::MD5Sum< ::pose_estimation::plan_service >
template<>
struct MD5Sum< ::pose_estimation::plan_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_estimation::plan_service >::value();
  }
  static const char* value(const ::pose_estimation::plan_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_estimation::plan_serviceRequest> should match
// service_traits::DataType< ::pose_estimation::plan_service >
template<>
struct DataType< ::pose_estimation::plan_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::pose_estimation::plan_service >::value();
  }
  static const char* value(const ::pose_estimation::plan_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_estimation::plan_serviceResponse> should match
// service_traits::MD5Sum< ::pose_estimation::plan_service >
template<>
struct MD5Sum< ::pose_estimation::plan_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_estimation::plan_service >::value();
  }
  static const char* value(const ::pose_estimation::plan_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_estimation::plan_serviceResponse> should match
// service_traits::DataType< ::pose_estimation::plan_service >
template<>
struct DataType< ::pose_estimation::plan_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::pose_estimation::plan_service >::value();
  }
  static const char* value(const ::pose_estimation::plan_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_ESTIMATION_MESSAGE_PLAN_SERVICE_H
