// Generated by gencpp from file sun_robot_msgs/ClikSetFixedJointsRequest.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTSREQUEST_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sun_robot_msgs
{
template <class ContainerAllocator>
struct ClikSetFixedJointsRequest_
{
  typedef ClikSetFixedJointsRequest_<ContainerAllocator> Type;

  ClikSetFixedJointsRequest_()
    : fixed_joints_names()  {
    }
  ClikSetFixedJointsRequest_(const ContainerAllocator& _alloc)
    : fixed_joints_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _fixed_joints_names_type;
  _fixed_joints_names_type fixed_joints_names;





  typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClikSetFixedJointsRequest_

typedef ::sun_robot_msgs::ClikSetFixedJointsRequest_<std::allocator<void> > ClikSetFixedJointsRequest;

typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetFixedJointsRequest > ClikSetFixedJointsRequestPtr;
typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetFixedJointsRequest const> ClikSetFixedJointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fixed_joints_names == rhs.fixed_joints_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e45467b1c923ef1fd997a83fc03563f";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e45467b1c923ef1ULL;
  static const uint64_t static_value2 = 0xfd997a83fc03563fULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_robot_msgs/ClikSetFixedJointsRequest";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] fixed_joints_names\n"
;
  }

  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fixed_joints_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClikSetFixedJointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_robot_msgs::ClikSetFixedJointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "fixed_joints_names[]" << std::endl;
    for (size_t i = 0; i < v.fixed_joints_names.size(); ++i)
    {
      s << indent << "  fixed_joints_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.fixed_joints_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTSREQUEST_H
