// Generated by gencpp from file sun_robot_msgs/ClikSetFixedJoints.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTS_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTS_H

#include <ros/service_traits.h>


#include <sun_robot_msgs/ClikSetFixedJointsRequest.h>
#include <sun_robot_msgs/ClikSetFixedJointsResponse.h>


namespace sun_robot_msgs
{

struct ClikSetFixedJoints
{

typedef ClikSetFixedJointsRequest Request;
typedef ClikSetFixedJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClikSetFixedJoints
} // namespace sun_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetFixedJoints > {
  static const char* value()
  {
    return "6214dae94e45bca5ba2b39af858137d6";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetFixedJoints&) { return value(); }
};

template<>
struct DataType< ::sun_robot_msgs::ClikSetFixedJoints > {
  static const char* value()
  {
    return "sun_robot_msgs/ClikSetFixedJoints";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetFixedJoints&) { return value(); }
};


// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetFixedJointsRequest> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetFixedJoints >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetFixedJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetFixedJoints >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetFixedJointsRequest> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetFixedJoints >
template<>
struct DataType< ::sun_robot_msgs::ClikSetFixedJointsRequest>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetFixedJoints >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetFixedJointsResponse> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetFixedJoints >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetFixedJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetFixedJoints >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetFixedJointsResponse> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetFixedJoints >
template<>
struct DataType< ::sun_robot_msgs::ClikSetFixedJointsResponse>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetFixedJoints >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetFixedJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKSETFIXEDJOINTS_H
