// Generated by gencpp from file sun_robot_msgs/ClikGetState.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKGETSTATE_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKGETSTATE_H

#include <ros/service_traits.h>


#include <sun_robot_msgs/ClikGetStateRequest.h>
#include <sun_robot_msgs/ClikGetStateResponse.h>


namespace sun_robot_msgs
{

struct ClikGetState
{

typedef ClikGetStateRequest Request;
typedef ClikGetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClikGetState
} // namespace sun_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_robot_msgs::ClikGetState > {
  static const char* value()
  {
    return "d91a0f07be437a20a6af62e12e2fad5a";
  }

  static const char* value(const ::sun_robot_msgs::ClikGetState&) { return value(); }
};

template<>
struct DataType< ::sun_robot_msgs::ClikGetState > {
  static const char* value()
  {
    return "sun_robot_msgs/ClikGetState";
  }

  static const char* value(const ::sun_robot_msgs::ClikGetState&) { return value(); }
};


// service_traits::MD5Sum< ::sun_robot_msgs::ClikGetStateRequest> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikGetState >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikGetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikGetState >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikGetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikGetStateRequest> should match
// service_traits::DataType< ::sun_robot_msgs::ClikGetState >
template<>
struct DataType< ::sun_robot_msgs::ClikGetStateRequest>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikGetState >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikGetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_robot_msgs::ClikGetStateResponse> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikGetState >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikGetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikGetState >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikGetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikGetStateResponse> should match
// service_traits::DataType< ::sun_robot_msgs::ClikGetState >
template<>
struct DataType< ::sun_robot_msgs::ClikGetStateResponse>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikGetState >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikGetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKGETSTATE_H
