// Generated by gencpp from file sun_robot_msgs/ClikSetMode.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKSETMODE_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKSETMODE_H

#include <ros/service_traits.h>


#include <sun_robot_msgs/ClikSetModeRequest.h>
#include <sun_robot_msgs/ClikSetModeResponse.h>


namespace sun_robot_msgs
{

struct ClikSetMode
{

typedef ClikSetModeRequest Request;
typedef ClikSetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClikSetMode
} // namespace sun_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetMode > {
  static const char* value()
  {
    return "63bcd8541111fcf71e8171764caa9288";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetMode&) { return value(); }
};

template<>
struct DataType< ::sun_robot_msgs::ClikSetMode > {
  static const char* value()
  {
    return "sun_robot_msgs/ClikSetMode";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetMode&) { return value(); }
};


// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetModeRequest> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetMode >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetMode >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetModeRequest> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetMode >
template<>
struct DataType< ::sun_robot_msgs::ClikSetModeRequest>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetMode >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetModeResponse> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetMode >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetMode >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetModeResponse> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetMode >
template<>
struct DataType< ::sun_robot_msgs::ClikSetModeResponse>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetMode >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKSETMODE_H
