// Generated by gencpp from file sun_robot_msgs/ClikSetSecondaryObj.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJ_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJ_H

#include <ros/service_traits.h>


#include <sun_robot_msgs/ClikSetSecondaryObjRequest.h>
#include <sun_robot_msgs/ClikSetSecondaryObjResponse.h>


namespace sun_robot_msgs
{

struct ClikSetSecondaryObj
{

typedef ClikSetSecondaryObjRequest Request;
typedef ClikSetSecondaryObjResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClikSetSecondaryObj
} // namespace sun_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObj > {
  static const char* value()
  {
    return "c07b3a4257a25972a24b9bc4876a5736";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObj&) { return value(); }
};

template<>
struct DataType< ::sun_robot_msgs::ClikSetSecondaryObj > {
  static const char* value()
  {
    return "sun_robot_msgs/ClikSetSecondaryObj";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObj&) { return value(); }
};


// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObjRequest> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObj >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObjRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObj >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetSecondaryObjRequest> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetSecondaryObj >
template<>
struct DataType< ::sun_robot_msgs::ClikSetSecondaryObjRequest>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetSecondaryObj >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObjResponse> should match
// service_traits::MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObj >
template<>
struct MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObjResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObj >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::ClikSetSecondaryObjResponse> should match
// service_traits::DataType< ::sun_robot_msgs::ClikSetSecondaryObj >
template<>
struct DataType< ::sun_robot_msgs::ClikSetSecondaryObjResponse>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::ClikSetSecondaryObj >::value();
  }
  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJ_H
