// Generated by gencpp from file sun_robot_msgs/ClikSetSecondaryObjResponse.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJRESPONSE_H
#define SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sun_robot_msgs
{
template <class ContainerAllocator>
struct ClikSetSecondaryObjResponse_
{
  typedef ClikSetSecondaryObjResponse_<ContainerAllocator> Type;

  ClikSetSecondaryObjResponse_()
    : success(false)  {
    }
  ClikSetSecondaryObjResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClikSetSecondaryObjResponse_

typedef ::sun_robot_msgs::ClikSetSecondaryObjResponse_<std::allocator<void> > ClikSetSecondaryObjResponse;

typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetSecondaryObjResponse > ClikSetSecondaryObjResponsePtr;
typedef boost::shared_ptr< ::sun_robot_msgs::ClikSetSecondaryObjResponse const> ClikSetSecondaryObjResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_robot_msgs/ClikSetSecondaryObjResponse";
  }

  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClikSetSecondaryObjResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_robot_msgs::ClikSetSecondaryObjResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_CLIKSETSECONDARYOBJRESPONSE_H
