// Generated by gencpp from file sun_robot_msgs/JointTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_JOINTTRAJECTORYGOAL_H
#define SUN_ROBOT_MSGS_MESSAGE_JOINTTRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace sun_robot_msgs
{
template <class ContainerAllocator>
struct JointTrajectoryGoal_
{
  typedef JointTrajectoryGoal_<ContainerAllocator> Type;

  JointTrajectoryGoal_()
    : trajectory()
    , sampling_freq(0.0)
    , use_exponential_junction(false)
    , initial_joints()
    , junction_time_constant(0.0)  {
    }
  JointTrajectoryGoal_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)
    , sampling_freq(0.0)
    , use_exponential_junction(false)
    , initial_joints(_alloc)
    , junction_time_constant(0.0)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef double _sampling_freq_type;
  _sampling_freq_type sampling_freq;

   typedef uint8_t _use_exponential_junction_type;
  _use_exponential_junction_type use_exponential_junction;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _initial_joints_type;
  _initial_joints_type initial_joints;

   typedef double _junction_time_constant_type;
  _junction_time_constant_type junction_time_constant;





  typedef boost::shared_ptr< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointTrajectoryGoal_

typedef ::sun_robot_msgs::JointTrajectoryGoal_<std::allocator<void> > JointTrajectoryGoal;

typedef boost::shared_ptr< ::sun_robot_msgs::JointTrajectoryGoal > JointTrajectoryGoalPtr;
typedef boost::shared_ptr< ::sun_robot_msgs::JointTrajectoryGoal const> JointTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return lhs.trajectory == rhs.trajectory &&
    lhs.sampling_freq == rhs.sampling_freq &&
    lhs.use_exponential_junction == rhs.use_exponential_junction &&
    lhs.initial_joints == rhs.initial_joints &&
    lhs.junction_time_constant == rhs.junction_time_constant;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f432036db786cbab1e03854cd9964ae";
  }

  static const char* value(const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f432036db786cbaULL;
  static const uint64_t static_value2 = 0xb1e03854cd9964aeULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_robot_msgs/JointTrajectoryGoal";
  }

  static const char* value(const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"trajectory_msgs/JointTrajectory trajectory\n"
"float64 sampling_freq\n"
"\n"
"# if exponential_junction the trajectory will be considered a nominal one q_N(t)\n"
"# the actual trajectory q(t) will be\n"
"# q(t) = (initial_joints - q_N(t))*exp(-(t-t0)/junction_time_constant) + q_N(t)\n"
"# NOTE: initial_joints must be ordered as the joints in the trajectory\n"
"bool use_exponential_junction\n"
"float64[] initial_joints\n"
"float64 junction_time_constant\n"
"\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
      stream.next(m.sampling_freq);
      stream.next(m.use_exponential_junction);
      stream.next(m.initial_joints);
      stream.next(m.junction_time_constant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_robot_msgs::JointTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "sampling_freq: ";
    Printer<double>::stream(s, indent + "  ", v.sampling_freq);
    s << indent << "use_exponential_junction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_exponential_junction);
    s << indent << "initial_joints[]" << std::endl;
    for (size_t i = 0; i < v.initial_joints.size(); ++i)
    {
      s << indent << "  initial_joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.initial_joints[i]);
    }
    s << indent << "junction_time_constant: ";
    Printer<double>::stream(s, indent + "  ", v.junction_time_constant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_JOINTTRAJECTORYGOAL_H
