// Generated by gencpp from file sun_robot_msgs/SetEndEffector.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTOR_H
#define SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTOR_H

#include <ros/service_traits.h>


#include <sun_robot_msgs/SetEndEffectorRequest.h>
#include <sun_robot_msgs/SetEndEffectorResponse.h>


namespace sun_robot_msgs
{

struct SetEndEffector
{

typedef SetEndEffectorRequest Request;
typedef SetEndEffectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEndEffector
} // namespace sun_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sun_robot_msgs::SetEndEffector > {
  static const char* value()
  {
    return "8627ab15409195513039221bc8434cb0";
  }

  static const char* value(const ::sun_robot_msgs::SetEndEffector&) { return value(); }
};

template<>
struct DataType< ::sun_robot_msgs::SetEndEffector > {
  static const char* value()
  {
    return "sun_robot_msgs/SetEndEffector";
  }

  static const char* value(const ::sun_robot_msgs::SetEndEffector&) { return value(); }
};


// service_traits::MD5Sum< ::sun_robot_msgs::SetEndEffectorRequest> should match
// service_traits::MD5Sum< ::sun_robot_msgs::SetEndEffector >
template<>
struct MD5Sum< ::sun_robot_msgs::SetEndEffectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::SetEndEffector >::value();
  }
  static const char* value(const ::sun_robot_msgs::SetEndEffectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::SetEndEffectorRequest> should match
// service_traits::DataType< ::sun_robot_msgs::SetEndEffector >
template<>
struct DataType< ::sun_robot_msgs::SetEndEffectorRequest>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::SetEndEffector >::value();
  }
  static const char* value(const ::sun_robot_msgs::SetEndEffectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sun_robot_msgs::SetEndEffectorResponse> should match
// service_traits::MD5Sum< ::sun_robot_msgs::SetEndEffector >
template<>
struct MD5Sum< ::sun_robot_msgs::SetEndEffectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sun_robot_msgs::SetEndEffector >::value();
  }
  static const char* value(const ::sun_robot_msgs::SetEndEffectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sun_robot_msgs::SetEndEffectorResponse> should match
// service_traits::DataType< ::sun_robot_msgs::SetEndEffector >
template<>
struct DataType< ::sun_robot_msgs::SetEndEffectorResponse>
{
  static const char* value()
  {
    return DataType< ::sun_robot_msgs::SetEndEffector >::value();
  }
  static const char* value(const ::sun_robot_msgs::SetEndEffectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTOR_H
