// Generated by gencpp from file sun_robot_msgs/SetEndEffectorRequest.msg
// DO NOT EDIT!


#ifndef SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTORREQUEST_H
#define SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace sun_robot_msgs
{
template <class ContainerAllocator>
struct SetEndEffectorRequest_
{
  typedef SetEndEffectorRequest_<ContainerAllocator> Type;

  SetEndEffectorRequest_()
    : n_pose_ee()  {
    }
  SetEndEffectorRequest_(const ContainerAllocator& _alloc)
    : n_pose_ee(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _n_pose_ee_type;
  _n_pose_ee_type n_pose_ee;





  typedef boost::shared_ptr< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEndEffectorRequest_

typedef ::sun_robot_msgs::SetEndEffectorRequest_<std::allocator<void> > SetEndEffectorRequest;

typedef boost::shared_ptr< ::sun_robot_msgs::SetEndEffectorRequest > SetEndEffectorRequestPtr;
typedef boost::shared_ptr< ::sun_robot_msgs::SetEndEffectorRequest const> SetEndEffectorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.n_pose_ee == rhs.n_pose_ee;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator1> & lhs, const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sun_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9afee90ebda7bd515b62e6acadb7b35";
  }

  static const char* value(const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9afee90ebda7bd5ULL;
  static const uint64_t static_value2 = 0x15b62e6acadb7b35ULL;
};

template<class ContainerAllocator>
struct DataType< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sun_robot_msgs/SetEndEffectorRequest";
  }

  static const char* value(const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose n_pose_ee #End Effector Pose w.r.t. link n\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n_pose_ee);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEndEffectorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sun_robot_msgs::SetEndEffectorRequest_<ContainerAllocator>& v)
  {
    s << indent << "n_pose_ee: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.n_pose_ee);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUN_ROBOT_MSGS_MESSAGE_SETENDEFFECTORREQUEST_H
