(cl:in-package sun_robot_msgs-srv)
(cl:export '(SECOND_OBJ_GAIN-VAL
          SECOND_OBJ_GAIN
          SECOND_OBJ_JOINT_VELOCITY_TOPIC-VAL
          SECOND_OBJ_JOINT_VELOCITY_TOPIC
          DESIRED_JOINT_CONFIGURATION-VAL
          DESIRED_JOINT_CONFIGURATION
          DESIRED_JOINT_CONFIGURATION_WEIGHTS-VAL
          DESIRED_JOINT_CONFIGURATION_WEIGHTS
          SUCCESS-VAL
          SUCCESS
))